import '@maptiler/sdk/dist/maptiler-sdk.css'
import '@maptiler/geocoding-control/style.css'

import type { Metadata } from 'next'
import { Toaster } from '@/components/ui/toaster'
import { Roboto } from 'next/font/google'
import './globals.css'
import { ToastContainer } from 'react-toastify'

const roboto = Roboto({
  subsets: ['latin'], // Escolha o conjunto de caracteres necessário
  weight: ['100', '300', '400', '500', '700', '900'], // Escolha os pesos necessários
  style: ['normal', 'italic'], // (Opcional) Para incluir estilos como itálico
})

export const metadata: Metadata = {
  title: 'Procura.aí',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased min-h-screen bg-white text-procura-ai-zinc`}
      >
        {/* <Header /> */}
        {children}
        <Toaster />
        <ToastContainer />
      </body>
    </html>
  )
}
